export const SAVE_SITE_GROUP_REQUEST = "SAVE_SITE_GROUP_REQUEST";
export const ADD_SITES_TO_GROUP_REQUEST = "SAVE_SITES_OF_GROUP_REQUEST";
export const FETCH_SITE_GROUP_REQUEST = "FETCH_SITE_GROUP_REQUEST";
// export const FETCH_SITE_GROUP_SITES_REQUEST = "FETCH_SITE_GROUP_SITES_REQUEST";
export const UPDATE_SITE_GROUP_REQUEST = "UPDATE_SITE_GROUP_REQUEST";
export const DELETE_SITE_GROUP_REQUEST = "DELETE_SITE_GROUP_REQUEST";
export const DELETE_SITES_OF_GROUP_REQUEST = "DELETE_SITES_OF_GROUP_REQUEST";
export const SITE_GROUP_SUCCESS = "SITE_GROUP_SUCCESS";
export const SITE_GROUP_FAILURE = "SITE_GROUP_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";