export const SAVE_SITE_GROUP_REQUEST = "SAVE_SITE_GROUP_REQUEST";
export const ADD_SITES_TO_GROUP_REQUEST = "SAVE_SITES_OF_GROUP_REQUEST";
export const FETCH_SITE_GROUP_REQUEST = "FETCH_SITE_GROUP_REQUEST";
export const UPDATE_SITE_GROUP_REQUEST = "UPDATE_SITE_GROUP_REQUEST";
export const DELETE_SITE_GROUP_REQUEST = "DELETE_SITE_GROUP_REQUEST";
export const DELETE_SITES_OF_GROUP_REQUEST = "DELETE_SITES_OF_GROUP_REQUEST";
export const SITE_GROUP_SUCCESS = "SITE_GROUP_SUCCESS";
export const SITE_GROUP_FAILURE = "SITE_GROUP_FAILURE";