export const REGISTER_EMAIL_REQUEST = "REGISTER_EMAIL_REQUEST";
export const UNREGISTER_EMAIL_REQUEST = "UNREGISTER_EMAIL_REQUEST";
export const EMAIL_SUCCESS = "EMAIL_SUCCESS";
export const EMAIL_FAILURE = "EMAIL_FAILURE";